# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDMxMWVlZDM3ODdmOWYxYmUzOWQ1MWFjNDJlMTIyYmMzNjU2ZWE5YWI3OWFmN2U4Y2Y2N2I4NWFkYjlhZDczNmFhOTJjZGRkMmEyNGZjZjkzMDU2NGVmMTUwNWQ5NDlhODgwZmY0YjRjZWU1YWU2MjM0YjdjOTg0YWM3NjQ0YmE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
